// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Syncify.Sync.Infrastructure.Persistence;

#nullable disable

namespace Syncify.Sync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260407075243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Syncify.Sync.Infrastructure.Persistence.Entities.SyncRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CopyTitle")
                        .HasColumnType("boolean")
                        .HasColumnName("copy_title");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("custom_title");

                    b.Property<string>("FilterPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_policy");

                    b.Property<Guid>("SourceCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_calendar_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SyncCursor")
                        .HasColumnType("text")
                        .HasColumnName("sync_cursor");

                    b.Property<Guid>("TargetCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_calendar_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("sync_rules", (string)null);
                });

            modelBuilder.Entity("Syncify.Sync.Infrastructure.Persistence.Entities.SyncedEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<DateTimeOffset>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<Guid>("SyncRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_rule_id");

                    b.Property<string>("TargetBlockId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_block_id");

                    b.HasKey("Id");

                    b.HasIndex("SyncRuleId", "SourceEventId")
                        .IsUnique();

                    b.ToTable("synced_events", (string)null);
                });

            modelBuilder.Entity("Syncify.Sync.Infrastructure.Persistence.Entities.SyncedEventEntity", b =>
                {
                    b.HasOne("Syncify.Sync.Infrastructure.Persistence.Entities.SyncRuleEntity", "SyncRule")
                        .WithMany()
                        .HasForeignKey("SyncRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRule");
                });
#pragma warning restore 612, 618
        }
    }
}
