<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Syncify.Connections.Application\Syncify.Connections.Application.csproj" />
    <ProjectReference Include="..\Syncify.Connections.Domain\Syncify.Connections.Domain.csproj" />
    <ProjectReference Include="..\Syncify.Shared\Syncify.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
